/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Day Mode ──
        'day-bg':        '#FAF7F2',
        'day-surface':   '#FFFFFF',
        'day-primary':   '#7C5CFC',
        'day-secondary': '#FF9A76',
        'day-accent':    '#36D6B5',
        'day-text':      '#2D2D3A',
        // ── Night Mode ──
        'night-bg':        '#0D0D0D',
        'night-surface':   '#1A1A1A',
        'night-primary':   '#9D85FF',
        'night-secondary': '#FFAA8A',
        'night-accent':    '#48F0D0',
        'night-text':      '#EDEDED',
        // ── Legacy aliases (keep compatibility) ──
        'soft-purple':  '#A78BFA',
        'lavender':     '#E9D5FF',
        'pastel-blue':  '#BFDBFE',
        'soft-pink':    '#FBCFE8',
        'warm-beige':   '#F5F5F4',
        'deep-purple':  '#7C5CFC',
        'muted-purple': '#DDD6FE',
        'dark-bg':      '#0D0D0D',
        'dark-card':    '#1A1A1A',
        'dark-card-hover': '#252525',
        'dark-border':  '#2A2A2A',
        'dark-text':    '#EDEDED',
        'dark-muted':   '#888888',
        'dark-accent':  '#9D85FF',
        // ── Mood aura colors ──
        'aura-happy':   '#FBBF24',
        'aura-calm':    '#34D399',
        'aura-sad':     '#60A5FA',
        'aura-angry':   '#F87171',
        'aura-tired':   '#A78BFA',
        'aura-excited': '#F472B6',
        'aura-anxious': '#8B5CF6',
      },
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
        body:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        mood:    ['"Kalam"', 'cursive'],
        sans:    ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'wellness-gradient':      'linear-gradient(135deg, #FAF7F2 0%, #F3EEFF 50%, #FFF5F0 100%)',
        'dark-wellness-gradient': 'linear-gradient(135deg, #0D0F1A 0%, #131436 50%, #0D0F1A 100%)',
        'card-gradient':          'linear-gradient(135deg, rgba(255,255,255,0.7) 0%, rgba(255,255,255,0.3) 100%)',
        'dark-card-gradient':     'linear-gradient(135deg, rgba(22,24,48,0.8) 0%, rgba(13,15,26,0.5) 100%)',
        'purple-gradient':        'linear-gradient(135deg, #A78BFA 0%, #7C5CFC 100%)',
        'blue-gradient':          'linear-gradient(135deg, #BFDBFE 0%, #93C5FD 100%)',
        'pink-gradient':          'linear-gradient(135deg, #FBCFE8 0%, #F9A8D4 100%)',
        'green-gradient':         'linear-gradient(135deg, #BBF7D0 0%, #34D399 100%)',
        'orange-gradient':        'linear-gradient(135deg, #FED7AA 0%, #FF9A76 100%)',
      },
      boxShadow: {
        'glass':      '0 8px 32px rgba(124, 92, 252, 0.12)',
        'glass-lg':   '0 16px 48px rgba(124, 92, 252, 0.18)',
        'mood':       '0 0 20px rgba(124, 92, 252, 0.5)',
        'card':       '0 4px 24px rgba(0, 0, 0, 0.05)',
        'card-hover': '0 8px 40px rgba(124, 92, 252, 0.2)',
        'aura':       '0 0 60px 20px',
        'aura-lg':    '0 0 100px 40px',
      },
      animation: {
        'blob':        'blob 7s infinite',
        'blob-slow':   'blob 12s infinite',
        'float':       'float 6s ease-in-out infinite',
        'float-slow':  'float 9s ease-in-out infinite',
        'fade-in':     'fadeIn 0.6s ease-out',
        'slide-up':    'slideUp 0.5s ease-out',
        'pulse-soft':  'pulseSoft 3s ease-in-out infinite',
        'glow-pulse':  'glowPulse 3s ease-in-out infinite',
        'breathe':     'breathe 8s ease-in-out infinite',
        'ripple':      'ripple 1.5s ease-out forwards',
        'orb-float':   'orbFloat 6s ease-in-out infinite',
        'spin-slow':   'spin 8s linear infinite',
        'particle':    'particle 4s ease-in-out infinite',
      },
      keyframes: {
        blob: {
          '0%':   { transform: 'translate(0px, 0px) scale(1)' },
          '33%':  { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%':  { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%':      { transform: 'translateY(-12px)' },
        },
        fadeIn: {
          '0%':   { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.6' },
          '50%':      { opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 30px 10px var(--aura-color, rgba(124,92,252,0.3))' },
          '50%':      { boxShadow: '0 0 60px 20px var(--aura-color, rgba(124,92,252,0.5))' },
        },
        breathe: {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.8' },
          '50%':      { transform: 'scale(1.15)', opacity: '1' },
        },
        ripple: {
          '0%':   { transform: 'scale(0.8)', opacity: '1' },
          '100%': { transform: 'scale(2.5)', opacity: '0' },
        },
        orbFloat: {
          '0%, 100%': { transform: 'translateY(0) scale(1)' },
          '25%':      { transform: 'translateY(-8px) scale(1.02)' },
          '50%':      { transform: 'translateY(-4px) scale(1)' },
          '75%':      { transform: 'translateY(-10px) scale(1.01)' },
        },
        particle: {
          '0%':   { transform: 'translateY(0) translateX(0) scale(1)', opacity: '0' },
          '25%':  { opacity: '1' },
          '50%':  { transform: 'translateY(-30px) translateX(15px) scale(0.8)', opacity: '0.8' },
          '75%':  { opacity: '0.4' },
          '100%': { transform: 'translateY(-60px) translateX(-10px) scale(0.3)', opacity: '0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
