export const MOODS = [
  {
    id: 'happy',
    label: 'Happy',
    emoji: '😄',
    color: 'from-yellow-200 to-amber-300',
    bgColor: 'bg-amber-100',
    textColor: 'text-amber-700',
    glow: 'shadow-[0_0_20px_rgba(251,191,36,0.5)]',
    border: 'border-amber-300',
    chartColor: '#FCD34D',
    score: 9,
    auraColor: '#FBBF24',
    auraGlow: 'rgba(251,191,36,0.4)',
    particleColor: '#FDE68A',
    positive: true,
  },
  {
    id: 'calm',
    label: 'Calm',
    emoji: '😌',
    color: 'from-green-200 to-teal-300',
    bgColor: 'bg-teal-100',
    textColor: 'text-teal-700',
    glow: 'shadow-[0_0_20px_rgba(52,211,153,0.5)]',
    border: 'border-teal-300',
    chartColor: '#34D399',
    score: 8,
    auraColor: '#34D399',
    auraGlow: 'rgba(52,211,153,0.4)',
    particleColor: '#A7F3D0',
    positive: true,
  },
  {
    id: 'sad',
    label: 'Sad',
    emoji: '😢',
    color: 'from-blue-200 to-indigo-300',
    bgColor: 'bg-blue-100',
    textColor: 'text-blue-700',
    glow: 'shadow-[0_0_20px_rgba(96,165,250,0.5)]',
    border: 'border-blue-300',
    chartColor: '#60A5FA',
    score: 3,
    auraColor: '#60A5FA',
    auraGlow: 'rgba(96,165,250,0.4)',
    particleColor: '#BFDBFE',
    positive: false,
  },
  {
    id: 'angry',
    label: 'Angry',
    emoji: '😤',
    color: 'from-red-200 to-rose-300',
    bgColor: 'bg-rose-100',
    textColor: 'text-rose-700',
    glow: 'shadow-[0_0_20px_rgba(248,113,113,0.5)]',
    border: 'border-rose-300',
    chartColor: '#F87171',
    score: 2,
    auraColor: '#F87171',
    auraGlow: 'rgba(248,113,113,0.4)',
    particleColor: '#FECACA',
    positive: false,
  },
  {
    id: 'tired',
    label: 'Tired',
    emoji: '😴',
    color: 'from-purple-200 to-violet-300',
    bgColor: 'bg-violet-100',
    textColor: 'text-violet-700',
    glow: 'shadow-[0_0_20px_rgba(167,139,250,0.5)]',
    border: 'border-violet-300',
    chartColor: '#A78BFA',
    score: 4,
    auraColor: '#A78BFA',
    auraGlow: 'rgba(167,139,250,0.4)',
    particleColor: '#DDD6FE',
    positive: false,
  },
  {
    id: 'excited',
    label: 'Excited',
    emoji: '🤩',
    color: 'from-pink-200 to-fuchsia-300',
    bgColor: 'bg-fuchsia-100',
    textColor: 'text-fuchsia-700',
    glow: 'shadow-[0_0_20px_rgba(244,114,182,0.5)]',
    border: 'border-fuchsia-300',
    chartColor: '#F472B6',
    score: 10,
    auraColor: '#F472B6',
    auraGlow: 'rgba(244,114,182,0.4)',
    particleColor: '#FBCFE8',
    positive: true,
  },
  {
    id: 'anxious',
    label: 'Anxious',
    emoji: '😰',
    color: 'from-violet-200 to-purple-400',
    bgColor: 'bg-purple-100',
    textColor: 'text-purple-700',
    glow: 'shadow-[0_0_20px_rgba(139,92,246,0.5)]',
    border: 'border-purple-300',
    chartColor: '#8B5CF6',
    score: 3,
    auraColor: '#8B5CF6',
    auraGlow: 'rgba(139,92,246,0.4)',
    particleColor: '#C4B5FD',
    positive: false,
  },
];

export const INFLUENCES = [
  { id: 'work', label: 'Work', emoji: '💼' },
  { id: 'family', label: 'Family', emoji: '👨‍👩‍👧' },
  { id: 'health', label: 'Health', emoji: '💪' },
  { id: 'sleep', label: 'Sleep', emoji: '🌙' },
  { id: 'friends', label: 'Friends', emoji: '👫' },
  { id: 'diet', label: 'Diet', emoji: '🥗' },
  { id: 'hobbies', label: 'Hobbies', emoji: '🎨' },
  { id: 'nature', label: 'Nature', emoji: '🌿' },
];

export const ACTIVITIES = [
  {
    id: 'breathing',
    title: 'Breathing Exercise',
    description: 'Calm your mind with guided breathing techniques',
    iconId: 'breathing',
    gradient: 'from-sky-50 via-blue-50 to-indigo-50',
    iconBg: 'bg-sky-100',
    duration: '5 min',
    color: '#93C5FD',
    route: '/breathing',
  },
  {
    id: 'journal',
    title: 'Mindful Journal',
    description: 'Write freely about your thoughts and feelings',
    iconId: 'journal',
    gradient: 'from-purple-50 via-violet-50 to-fuchsia-50',
    iconBg: 'bg-violet-100',
    duration: '10 min',
    color: '#C4B5FD',
    route: '/check-in',
  },
  {
    id: 'meditation',
    title: 'Meditation',
    description: 'Find peace with a mindfulness session',
    iconId: 'meditation',
    gradient: 'from-emerald-50 via-teal-50 to-cyan-50',
    iconBg: 'bg-teal-100',
    duration: '15 min',
    color: '#6EE7B7',
    route: '/meditation',
  },
];

export const getMoodById = (id) => MOODS.find((m) => m.id === id);
export const getMoodByLabel = (label) => MOODS.find((m) => m.label === label);

export const getDayLabels = () => {
  const days = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const today = new Date().getDay();
  return Array.from({ length: 7 }, (_, i) => days[(today - 6 + i + 7) % 7]);
};
